name = "sharex-r2-cloudflare-workers"
account_id = "25169d5343500c4d212c73e2b92c6f33"
workers_dev = false
routes = [
	{pattern = "uploads.bayliss.app/*", zone_name = "bayliss.app"}
]

compatibility_date = "2022-04-22"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "sharex-uploads"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"
